### ISSUE TITLE
Gauge.depositFor/deposit: Siimlar logic

### ISSUE THREAD

**Issue by rareweasel** [yearn/veYFI#101]
I see very similar logic in these functions:

- Gauge.[depositFor](https://github.com/yearn/veYFI/blob/next_version/contracts/Gauge.sol#L357)
- Gauge.[deposit](https://github.com/yearn/veYFI/blob/next_version/contracts/Gauge.sol#L313)

Does it make sense to create an internal function passing `for` address, `sender` address, and `amount`?

**Comment by pandadefi** [comment]
@rareweasel PR created.
