### ISSUE TITLE
Question: BaseGauge.queuedRewards

### ISSUE THREAD

**Issue by rareweasel** [yearn/veYFI#102]
I know we added an event in [this pr](https://github.com/yearn/veYFI/commit/ba1e8d72ff4274a61b12bc81fe0b47c668d7815b), but I wonder how can we know we set `queuedRewards` to `0` [here](https://github.com/yearn/veYFI/blob/next_version/contracts/BaseGauge.sol#L137) or [here](https://github.com/yearn/veYFI/blob/next_version/contracts/BaseGauge.sol#L147) or `_amount` [here](https://github.com/yearn/veYFI/blob/next_version/contracts/BaseGauge.sol#L149).

**Comment by pandadefi** [comment]
Isn't it possible to read the value on every block?

**Comment by rareweasel** [comment]
> > queuedRewards
> 
> Isn't it possible to read the value on every block?
> 
> > _amount
> 
> Can't be zero and should match the transfer amount.


I meant when we set `queuedRewards = 0` or `queuedRewards = _amount`:

Yes, it is possible to call the function to get value in the subgraph, but it makes too much slower the sync process (more if we call it every block). That's why it would be better if we emit an event.

**Comment by pandadefi** [comment]
I prefer we don't add an other event, I know gas isn't that expensive but it's adding up with the one already emited.

**Comment by rareweasel** [comment]
And if we move [this event](https://github.com/yearn/veYFI/blob/next_version/contracts/BaseGauge.sol#L142) at the end of the function to include both values `_amount` and `queuedRewards`.
