### ISSUE TITLE
Add Indexed Keyword in Events

### ISSUE THREAD

**Issue by rareweasel** [yearn/veYFI#108]
Add the `indexed` keyword in these parameters (events):

- [VoteDelegation.Delegate](https://github.com/yearn/veYFI/blob/master/contracts/VoteDelegation.sol#L20): sender and recipient
- [VoteDelegation.DelegationRemoved](https://github.com/yearn/veYFI/blob/master/contracts/VoteDelegation.sol#L21): from and to
- [VoteDelegation.DelegationDurationIncreased](https://github.com/yearn/veYFI/blob/master/contracts/VoteDelegation.sol#L22): from and to

- [BaseGauge.RewardsQueued](https://github.com/yearn/veYFI/blob/master/contracts/BaseGauge.sol#L37): from
- [BaseGauge.UpdatedRewards](https://github.com/yearn/veYFI/blob/master/contracts/BaseGauge.sol#L40): account
- [BaseGauge.Sweep](https://github.com/yearn/veYFI/blob/master/contracts/BaseGauge.sol#L47): token

- [ExtraRewards.Initialized](https://github.com/yearn/veYFI/blob/master/contracts/ExtraReward.sol#L20): _gauge, rewardToken and owner.
- [Gauge](https://github.com/yearn/veYFI/blob/master/contracts/Gauge.sol#L50-L54): all addresses (Initialized event: only the owner, stakingToken and rewardToken parameters)
- [GaugeFactory](https://github.com/yearn/veYFI/blob/master/contracts/GaugeFactory.sol#L16-L17): all address parameters
- [Registry](https://github.com/yearn/veYFI/blob/master/contracts/Registry.sol#L25-L27): all address parameters
- [VotingEscrow](https://github.com/yearn/veYFI/blob/master/contracts/VotingEscrow.vy#L69-L78): all address parameters

**Comment by pandadefi** [comment]
[ExtraRewards.Initialized](https://github.com/yearn/veYFI/blob/master/contracts/ExtraReward.sol#L20): _gauge, rewardToken and owner.
[Gauge](https://github.com/yearn/veYFI/blob/master/contracts/Gauge.sol#L50-L54): all addresses (Initialized event: only the stakingToken and rewardToken parameters)

Why on one owner is indexed but not on the second one?

**Comment by rareweasel** [comment]
> [ExtraRewards.Initialized](https://github.com/yearn/veYFI/blob/master/contracts/ExtraReward.sol#L20): _gauge, rewardToken and owner. [Gauge](https://github.com/yearn/veYFI/blob/master/contracts/Gauge.sol#L50-L54): all addresses (Initialized event: only the stakingToken and rewardToken parameters)
> 
> Why on one owner is indexed but not on the second one?

Issue updated.

Note: You can only add 3 fields as indexed in events.
