### ISSUE TITLE
NextVe: Implements IMigrator Interface

### ISSUE THREAD

**Issue by rareweasel** [yearn/veYFI#109]
The `VotingEscrow.vy` contract uses a `Migrator` interface internally, but the current `test` implementation doesn't use an interface.

My suggestion is to create a `IMigrator.sol` interface and use it in the `NextVe.sol` `test` contract.

Note: It isn't a high priority. It is just to tracking and don't loss the tracking of the issue.

**Comment by pandadefi** [comment]
We will create it once we need it
