### ISSUE TITLE
Suggestion: Use `{...}`

### ISSUE THREAD

**Issue by rareweasel** [yearn/veYFI#110]
I would always use `{...}` in if/else/for/while/etc.

Sometime ago I had an issue with a linter/formatter that formatted an if without {..} incorrectly.

[Gauge._lockingRatio 1](https://github.com/yearn/veYFI/blob/master/contracts/Gauge.sol#L214)
[Gauge._lockingRatio 2](https://github.com/yearn/veYFI/blob/master/contracts/Gauge.sol#L217)
[Gauge._boostedBalanceOf](https://github.com/yearn/veYFI/blob/master/contracts/Gauge.sol#L287)
[VeYfiRewards._getReward](https://github.com/yearn/veYFI/blob/master/contracts/VeYfiRewards.sol#L131)

**Comment by pandadefi** [comment]
https://github.com/yearn/veYFI/commit/7fe15e84610db2bc8176b14613ac8f2e0d311b17
