### ISSUE TITLE
VoteDelegation._removeOldDelegation: Gas Consumption Analysis

### ISSUE THREAD

**Issue by rareweasel** [yearn/veYFI#112]
I see that an user can delegate up to 1000 [here](https://github.com/yearn/veYFI/blob/next_version/contracts/VoteDelegation.sol#L76).

If I as an user I want to remove the last one in the list. Do we know it is supported without getting an out of gas?

![image](https://user-images.githubusercontent.com/89795397/159550432-2f26ff16-b207-4dfc-8015-eaaa13f39b48.png)

**Comment by pandadefi** [comment]
Tried it is using 1881577 gas

**Comment by pandadefi** [comment]
@rareweasel comment?

**Comment by rareweasel** [comment]
> Tried it is using 1,881,577 gas

Excellent, could we add a test and assert the gas consumption? So, we can remember it in case we change it in the future.
