### ISSUE TITLE
Question:  Who is using IVeYfiRewardPool?

### ISSUE THREAD

**Issue by rareweasel** [yearn/veYFI#122]
We didn't find any contract that extends the `IVeYfiRewardPool.sol` interface.

`IVeYfiRewardPool.sol`
- `function queueNewRewards(uint256) external returns (bool);`

We found that `IBaseGauge.sol` interface also defines the same function and `BaseGauge.sol` implements it.

Do we need this `IVeYfiRewardPool` interface?

**Comment by pandadefi** [comment]
https://github.com/yearn/veYFI/commit/7fbec080041674e1c95c281796a912b7d2c5bd26
