### ISSUE TITLE
veYFIRewards reward calculation benefits regular claims.

### ISSUE THREAD

**Issue by chuddster** [yearn/veYFI#135]
Since the penalty of early withdrawal is distributed to the existing yfi stakers, shouldn't the distribution also depends on a yfi lockers veYFI weights at the time which a separate individual did early withdraw (and therefore lost some yfi to veyfi rewards)? The current implementation makes those who are periodically calling deposit/withdraw earn more rewards from penalties than those who don't. This is because, by the time someone claims penalties YFI, their veYFI balance could already be 0 as it decays.

[Line 67](https://github.com/yearn/veYFI/blob/79e53db7e130e1394e221e667452076d1fc3c09b/contracts/VeYfiRewards.sol#L67)

**Comment by pandadefi** [comment]
You are correct, this is one of the drawbacks of the system

If we were to distribute rewards when they are queued, we would need a snapshot of all user's balances to distribute accordingly which isn't possible.

If you have ideas on how to solve or mitigate the issue, please share.

**Comment by chuddster** [comment]
How about using [FeeDistributor](https://github.com/curvefi/curve-dao-contracts/blob/master/contracts/FeeDistributor.vy) from Curve? The logic is for distributing 50% of protocol revenue in 3CRV. How about using same thing but use penaltied YFI as reward in which [burn](https://github.com/curvefi/curve-dao-contracts/blob/3156684fd7ca424ec4c56b2c8d898b77afa78496/contracts/FeeDistributor.vy#L375) is called instead of donate?

**Comment by pandadefi** [comment]
This is great and simple to use. Maybe a `claimable` view function could be added.

**Comment by chuddster** [comment]
yeah I modified FeeDistributor to add a [claimable](https://github.com/ribbon-finance/ribbonomics/blob/d344d6752c1520f71aaf6600ecd376b6c8776c5e/contracts/FeeDistributor.vy#L306) method on-chain 

can_checkpoint_token should be turned on with [toggle_allow_checkpoint_token](https://github.com/ribbon-finance/ribbonomics/blob/d344d6752c1520f71aaf6600ecd376b6c8776c5e/contracts/FeeDistributor.vy#L472) on for burn() call to auto-checkpoint everything when its called. otherwise checkpoint() has to be called manually by admin.

**Comment by pandadefi** [comment]
> can_checkpoint_token should be turned on with [toggle_allow_checkpoint_token](https://github.com/ribbon-finance/ribbonomics/blob/d344d6752c1520f71aaf6600ecd376b6c8776c5e/contracts/FeeDistributor.vy#L472) on for burn() call to auto-checkpoint everything when its called. otherwise checkpoint() has to be called manually by admin.

Sorry, what I meant is why is `can_checkpoint_token` here in the first place, or could it be removed?

**Comment by chuddster** [comment]
I think it can be removed. Only reason for it to be off is if you don't want burn() to checkpoint everything. the tx you are pointing to is a `checkpoint_total_supply` call btw.

**Comment by pandadefi** [comment]
I think I got why the start point is 2 months prior to the deployment, it's done so that it will distribute rewards for the two months prior to the deployment. using `_checkpoint_token`.

**Comment by chuddster** [comment]
yep, for retroactive rewards. however I struggle to see the reason to do _checkpoint_token manually rather than through the initial burn?
