### ISSUE TITLE
[Gauge]: Trust assumption in gauge - owner has a power to rug reward in gauges

### ISSUE THREAD

**Issue by storming0x** [yearn/veYFI#159]
With method setVE
https://github.com/yearn/veYFI/blob/a1eb7ab4a86df05c5451ea64667d123869800f75/contracts/Gauge.sol#L131

Owner can potentially set VeToken contract to a mock token before/during rewards and boost specific accounts or change supply and other methods from veYFI that affect reward calculations.

e.g:
https://github.com/yearn/veYFI/blob/a1eb7ab4a86df05c5451ea64667d123869800f75/contracts/Gauge.sol#L433
https://github.com/yearn/veYFI/blob/a1eb7ab4a86df05c5451ea64667d123869800f75/contracts/Gauge.sol#L441

This is an important trust assumption, not sure what was the use case for the design around migrating veToken on specific gauges, if a migration even happens users may altogether withdraw from gauge vault shares and exit to new gauge.

I guess the option is to renounce ownership also losing sweep functionality, in any case that may be a good tradeoff

**Comment by banteg** [comment]
the solution is simple, this functionality should be removed and veyfi should be made immutable as i've shown is possible in #160.

**Comment by storming0x** [comment]
closed by #160
