### ISSUE TITLE
add a flag to keep the duration constant

### ISSUE THREAD

**Issue by banteg** [yearn/veYFI#161]
we should have a feature to keep the lock duration constant, this will bring more long-term alignment and it's a good quality of life upgrade for both the users and the integrators.

here is how it worked in nycypher staking contract:

- Wind down: on or off?
  - ON: Locked NU tokens are staked for a fixed lockup period. The reward rate decreases slightly every day as the lockup period diminishes. Locked tokens become liquid at the end of the lockup period and can be transferred or used to initiate a new stake and continue earning rewards.
  - OFF: Locked NU tokens are staked at a constant reward rate for a fixed lockup period. Wind Down must be turned ON to begin gradually moving toward unlocking the tokens.
- Restaking: on or off?
  - OFF: Rewards earned by the node are immediately available for use (liquid) and do not compound.
  - ON: Rewards earned by the node are automatically staked to the node to generate additional work and rewards. Rewards earned are unlocked at the same time as the original locked tokens.

source: https://www.coinbase.com/cloud/discover/solutions/nucypher-staking-scenarios

**Comment by pandadefi** [comment]
That's a great improvement from the original ve. Have you started working on it?
