### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by storming0x** [yearn/veYfi#21]
**Description**: 
veYFI repo code review

**Commit (hash)**:  https://github.com/yearn/veYfi/commit/83323bed1142c97e921b54e8d7d72ef1106d32ac

**Tag**:

**Scope**: (List link to files)
- VotingEscrow.vy
- Voter.sol
- VeYFIRewards.sol
- GaugeFactory.sol
- Gauge.sol
- ExtraReward.sol

**Additional References or Repo** (Link to underlying protocols or relevant documents):

Diff Curve's VotingEscrow.vy. https://www.diffchecker.com/6kTLsUYi

**Deployed Contract** (etherscan link): 

**Review Ongoing By**:
- [x] @storming0x 
- [ ] Dev 2

**Review Completed By**:
- [ ] @storming0x 
- [ ] Dev 2

**Comment by storming0x** [comment]
Suggestion:

Would remove underscore prefix to keep consistency with Curve's style.
https://github.com/yearn/veYfi/blob/83323bed1142c97e921b54e8d7d72ef1106d32ac/contracts/VotingEscrow.vy#L72

**Comment by storming0x** [comment]
Question:

Any benefit on using latest vyper version compared to curve's 0.2.4 existing one?

https://github.com/yearn/veYfi/blob/83323bed1142c97e921b54e8d7d72ef1106d32ac/contracts/VotingEscrow.vy#L1

Worried that 0.3.1 may be too fresh to use and 0.2.4 has been proven stable enough.

**Comment by storming0x** [comment]
Question:

Can you clarify here the reasoning  between changing the balanceOf implementation w binary search and the original curve's implementation?

veYFI balanceOf
https://github.com/yearn/veYfi/blob/83323bed1142c97e921b54e8d7d72ef1106d32ac/contracts/VotingEscrow.vy#L532

**Comment by storming0x** [comment]
Comment:

Potentially this method can accept address zero essentially locking withdraws and bricking several important interactions with the contract.

https://github.com/yearn/veYfi/blob/83323bed1142c97e921b54e8d7d72ef1106d32ac/contracts/VotingEscrow.vy#L141

**Comment by storming0x** [comment]
Comment:

This is not true, right?

https://github.com/yearn/veYfi/blob/83323bed1142c97e921b54e8d7d72ef1106d32ac/contracts/VotingEscrow.vy#L471

This method actually only works if the lock hasnt expired?

**Comment by storming0x** [comment]
Comment:

If block.timestamp == _locked.end

there's a small chance ´time_left´ == 0

so donate here:
https://github.com/yearn/veYfi/blob/83323bed1142c97e921b54e8d7d72ef1106d32ac/contracts/VotingEscrow.vy#L497

would revert having 'penalty' == 0

Smth good to test as edge case just to be sure expectations are correct.

**Comment by storming0x** [comment]
Question:

Just to be clear

https://github.com/yearn/veYfi/blob/83323bed1142c97e921b54e8d7d72ef1106d32ac/contracts/VotingEscrow.vy#L477

here we always want to take the minimum penalty out of the two options?

**Comment by storming0x** [comment]
Comment:

Update documentation here on expectations regarding penalty?

https://github.com/yearn/veYfi/blob/83323bed1142c97e921b54e8d7d72ef1106d32ac/contracts/VotingEscrow.vy#L470

**Comment by pandadefi** [comment]
> Suggestion:
> 
> Would remove underscore prefix to keep consistency with Curve's style.
> 
> https://github.com/yearn/veYfi/blob/83323bed1142c97e921b54e8d7d72ef1106d32ac/contracts/VotingEscrow.vy#L72

`from`is a protected keyword in vyper.

**Comment by pandadefi** [comment]
> Question:
> 
> Any benefit on using latest vyper version compared to curve's 0.2.4 existing one?
> 
> https://github.com/yearn/veYfi/blob/83323bed1142c97e921b54e8d7d72ef1106d32ac/contracts/VotingEscrow.vy#L1
> 
> Worried that 0.3.1 may be too fresh to use and 0.2.4 has been proven stable enough.

That's something we can discuss and adjust last minute, the only benefits are bytecode size wise.

**Comment by pandadefi** [comment]
> Can you clarify here the reasoning between changing the balanceOf implementation w binary search and the original curve's implementation?

balanceOfAt -> based on block
balanceOf -> based on time

The oriiginal balanceOf implementation wasn't able to look for a balanceOf after an update of a lock.

**Comment by pandadefi** [comment]
> Comment:
> 
> If block.timestamp == _locked.end
> 
> there's a small chance ´time_left´ == 0
> 
> so donate here:
> 
> https://github.com/yearn/veYfi/blob/83323bed1142c97e921b54e8d7d72ef1106d32ac/contracts/VotingEscrow.vy#L497
> 
> would revert having 'penalty' == 0
> 
> Smth good to test as edge case just to be sure expectations are correct.

There is a strict check to make sure time isn't zero `assert block.timestamp < _locked.end, "lock expired"`

But If it's really close to zero indeed with the rounding you might get a penalty to zero if your balance of YFI is really small.

https://github.com/yearn/veYfi/commit/1e890b308dc2e6b02874e122ed20a28ea17b5403

**Comment by pandadefi** [comment]
> Question:
> 
> Just to be clear
> 
> https://github.com/yearn/veYfi/blob/83323bed1142c97e921b54e8d7d72ef1106d32ac/contracts/VotingEscrow.vy#L477
> 
> here we always want to take the minimum penalty out of the two options?

Yes you pay at most 75%. If you have locked for 4 years, the first year you pay 75% then it will decrease.

**Comment by pandadefi** [comment]
> Potentially this method can accept address zero essentially locking withdraws and bricking several important interactions with the contract.

https://github.com/yearn/veYfi/commit/910ac6df62beab1ebfe811073dace443524ec80e

**Comment by storming0x** [comment]
closing the issue and moving to board
