### ISSUE TITLE
question: VeYFIRewards around _getReward internal method and design

### ISSUE THREAD

**Issue by storming0x** [yearn/veYFI#33]
Question:

https://github.com/yearn/veYfi/blob/d42be4f6cbad7dd936d8b461a4c6cd5e4bddd61a/contracts/VeYfiRewards.sol#L140

_getReward is an internal method that is called from several external entry points:

getReward()
getReward(bool _lock) 
getRewardFor(address account) 

it also uses the modifier updateReward(address _account), which in the external method is restricted to be call only by
the ve contract here:

https://github.com/yearn/veYfi/blob/d42be4f6cbad7dd936d8b461a4c6cd5e4bddd61a/contracts/VeYfiRewards.sol#L102

Given this setup is the intended design that essentially through the getReward public entry points any account can updateRewards on any account at any point in time? Are there any consequences of any accounts updating rewards for anyone else or mutating lastUpdateTime every block?

The require for restricted access seems to want to restricted to only ve instead of making it public.

**Comment by pandadefi** [comment]
`updateReward` is used to signal a change of balance so that a reward snapshot is taken.

When claiming rewards `getReward` is called by an account to pull his rewards out of the pool triggering an `updateReward` so that `userRewardPerTokenPaid[account] = rewardPerTokenStored;` is updated.

**Comment by storming0x** [comment]
> When claiming rewards `getReward` is called by an account to pull his rewards out of the pool triggering an `updateReward` so that `userRewardPerTokenPaid[account] = rewardPerTokenStored;` is updated.

understand, but in the case of getRewardFor here:

https://github.com/yearn/veYfi/blob/d42be4f6cbad7dd936d8b461a4c6cd5e4bddd61a/contracts/VeYfiRewards.sol#L114

I can update your rewards and push your rewards to your account, was wondering if this is intended design (i think that is the intention), since the require caught my attention restricting it to veToken contract in the referenced line

**Comment by pandadefi** [comment]
It's only to be used with a contract that will get all the rewards for you in a singe call.

**Comment by storming0x** [comment]
undesrtand and closing the issue
