### ISSUE TITLE
loss rewards appear to be calculated incorrectly in ExtraRewards.sol

### ISSUE THREAD

**Issue by anticlimactic** [yearn/veYfi#37]
In `ExtraRewards.sol`, both `_newEarning()` and `_maxEarning()` have the same code. I believe `_maxEarning()` should be calculated using the earnings based on `gauge.balanceOf(account)` instead of `gauge.boostedBalanceOf(account)`

https://github.com/yearn/veYfi/blob/68cb8148a5f3305ed5d43e3f6d026971649c53de/contracts/ExtraReward.sol#L103

If the code is left as is, then this line in `_updateReward()` always equals zero.
https://github.com/yearn/veYfi/blob/68cb8148a5f3305ed5d43e3f6d026971649c53de/contracts/ExtraReward.sol#L63

**Comment by pandadefi** [comment]
https://github.com/yearn/veYfi/commit/ac3fdd3c93dc84031295845014d71229a32b1f80
