### ISSUE TITLE
Gauge.sol can accept 0x0 address as rewardManager

### ISSUE THREAD

**Issue by storming0x** [yearn/veYFI#40]
RewardManager can be 0x0 

https://github.com/yearn/veYfi/blob/02b7a24776be0bae227f988fbb0d8d7e5b92e0b5/contracts/Gauge.sol#L171

**Comment by pandadefi** [comment]
https://github.com/yearn/veYfi/commit/74857b5820d6e35aaecc1d998ca2472a525444e2
