### ISSUE TITLE
Gauge.sol inconsistent prefix naming

### ISSUE THREAD

**Issue by storming0x** [yearn/veYFI#42]
https://github.com/yearn/veYfi/blob/02b7a24776be0bae227f988fbb0d8d7e5b92e0b5/contracts/Gauge.sol#L61

https://github.com/yearn/veYfi/blob/02b7a24776be0bae227f988fbb0d8d7e5b92e0b5/contracts/Gauge.sol#L58

https://github.com/yearn/veYfi/blob/02b7a24776be0bae227f988fbb0d8d7e5b92e0b5/contracts/Gauge.sol#L86

**Comment by pandadefi** [comment]
[stakingToken_ is in the initializer ](https://github.com/yearn/veYfi/commit/13e2d801259e00213b11fe96249fff3ce6adb96f)
