### ISSUE TITLE
Gauge.sol rewardManager can add a bad extraRewards that locks user vault shares

### ISSUE THREAD

**Issue by storming0x** [yearn/veYFI#44]
https://github.com/yearn/veYfi/blob/02b7a24776be0bae227f988fbb0d8d7e5b92e0b5/contracts/Gauge.sol#L387

Since this line forces to update snapshot on extra reward, theres no emergency exit option for users to unstake shares,
Should this line and block be under claim flag scope here instead?

https://github.com/yearn/veYfi/blob/02b7a24776be0bae227f988fbb0d8d7e5b92e0b5/contracts/Gauge.sol#L394

**Comment by pandadefi** [comment]
I see the issue but I do not see a solution, If we add a mechanism for emergencyWithdraw the snapshot won't be taken and the user would be able to keep claiming extra rewards without any funds in the gauge.
