### ISSUE TITLE
Question Gauge.sol and GaugeFactory.sol can create multiple gauges for same stakingToken (vault)?

### ISSUE THREAD

**Issue by storming0x** [yearn/veYFI#45]
Is this intended design?

https://github.com/yearn/veYfi/blob/02b7a24776be0bae227f988fbb0d8d7e5b92e0b5/contracts/GaugeFactory.sol#L41

**Comment by pandadefi** [comment]
It's intended, not likely to happen but I won't see any reason to block this from happening.

**Comment by anticlimactic** [comment]
not sure if this is relevant, but the only function that calls `createGauge` in the repo is in Voter.sol and has a require guard that checks if a gauge already exists per vault (i.e. if the gauge already exists, it reverts) as each vault can only have one gauge mapped to it.

https://github.com/yearn/veYfi/blob/6c42045ddd727a013b5c046e7fd71addd968d156/contracts/Voter.sol#L19
https://github.com/yearn/veYfi/blob/6c42045ddd727a013b5c046e7fd71addd968d156/contracts/Voter.sol#L212
