### ISSUE TITLE
Question GaugeFactory.sol gauges are not exclusive to yearn vaults?

### ISSUE THREAD

**Issue by storming0x** [yearn/veYFI#46]
May be part of the intended design, but i dont see checks to ensure the vaults are exclusively yearn vaults, etc.

https://github.com/yearn/veYfi/blob/02b7a24776be0bae227f988fbb0d8d7e5b92e0b5/contracts/GaugeFactory.sol#L42

**Comment by pandadefi** [comment]
We will have to rely on the registry which will most likely change on the next version. 
Code says it's vault but it can be any token and I think that's a good thing if we want to give rewards let's say to YFI-ETH LP.
