### ISSUE TITLE
Gauge.sol: updateRewardManager vs setRewardManager

### ISSUE THREAD

**Issue by anticlimactic** [yearn/veYfi#47]
is there any reason why this function (`updateRewardManager`) is preferred over `setRewardManager`? would we ever want to update reward manager without emitting an event?

may fix #40 

https://github.com/yearn/veYfi/blob/02b7a24776be0bae227f988fbb0d8d7e5b92e0b5/contracts/Gauge.sol#L171

https://github.com/yearn/veYfi/blob/02b7a24776be0bae227f988fbb0d8d7e5b92e0b5/contracts/Gauge.sol#L598

**Comment by pandadefi** [comment]
double check the code, setRewardManager is only called if rewardManager isn't set.

**Comment by pandadefi** [comment]
I have to think about it

**Comment by pandadefi** [comment]
https://github.com/yearn/veYfi/commit/74857b5820d6e35aaecc1d998ca2472a525444e2
