### ISSUE TITLE
Some public functions call internal function with the same signature

### ISSUE THREAD

**Issue by gmridul** [yearn/veYfi#51]
For example

https://github.com/gmridul/veYfi/blob/6c42045ddd727a013b5c046e7fd71addd968d156/contracts/Gauge.sol#L198-L200

We can avoid having `internal` functions in such cases.

Similarly, for we can make `_totalSupply` a public variable and avoid having a separate getter function `totalSupply()`: 

https://github.com/gmridul/veYfi/blob/master/contracts/Gauge.sol#L104

Let me know if this is not violating some code guideline and I can make these changes.

**Comment by gmridul** [comment]
I can close this PR if the changes are not needed.

**Comment by pandadefi** [comment]
Using an internal function is cheaper than a public function that is why it's like that.
