### ISSUE TITLE
Voter can delegate to themselves in Voter.sol

### ISSUE THREAD

**Issue by anticlimactic** [yearn/veYfi#55]
There is no require guard in `delegate` that stops a voter from delegating to themselves. It doesn't appear to cause any issues when it comes to voting but I wasn't sure if this was intentional or not.

https://github.com/yearn/veYfi/blob/6c42045ddd727a013b5c046e7fd71addd968d156/contracts/Voter.sol#L257

**Comment by pandadefi** [comment]
Should be ok
