### ISSUE TITLE
test_voting_escrow.py doesn't use account fixtures

### ISSUE THREAD

**Issue by anticlimactic** [yearn/veYfi#56]
This may make it more annoying to reason about the tests, especially once you are familiar with how the rest of the tests/account fixtures work. Is this worthwhile fixing for consistency?

I am referring to the use of `alice` and `bob` as accounts vs. `whale`, `shark`, `gov` etc which are present in all the other tests.

**Comment by pandadefi** [comment]
Code was copied from curve codebase that's why it's not using the same naming feel free to change it
