### ISSUE TITLE
Voter.sol is gov argument intended to be different from gov field

### ISSUE THREAD

**Issue by storming0x** [yearn/veYFI#57]
Here:
https://github.com/yearn/veYfi/blob/d8fb8fc901bb4cac557377a0f35fff299ddb126d/contracts/Voter.sol#L208

Is the gov arg for a given gauge intended to be different at any point in time or we can omit it?

**Comment by pandadefi** [comment]
I don't know I like the flexibility of being able to set it.

**Comment by rareweasel** [comment]
I also had this question while I was reviewing the code.

It makes me ask, what would be the potential scenario where we use a different `gov` address?

If you ask me, I would keep in simple, and use only one `gov`, because it might open a risky door.

**Comment by pandadefi** [comment]
Closing with the migration to off-chain voting.
