### ISSUE TITLE
Voter.sol is this missing an update gauge method?

### ISSUE THREAD

**Issue by storming0x** [yearn/veYFI#60]
May be wrong since im basing this from solidly and curve contracts.

Here:
https://github.com/yearn/veYfi/blob/d8fb8fc901bb4cac557377a0f35fff299ddb126d/contracts/Voter.sol#L139

i don't see a similar method like the one used here:

https://github.com/solidlyexchange/solidly/blob/eac1ef02ca8736138b25062c02646ea43d5bb6e4/contracts/BaseV1-voter.sol#L193

https://github.com/solidlyexchange/solidly/blob/eac1ef02ca8736138b25062c02646ea43d5bb6e4/contracts/BaseV1-voter.sol#L314

**Comment by pandadefi** [comment]
It seems to be used to adjust distribution which I think we will do offchain.

**Comment by pandadefi** [comment]
Closing with the migration to off-chain voting.
