### ISSUE TITLE
Voter.sol how are the vote results executed and distributed to gauges in rewards?

### ISSUE THREAD

**Issue by storming0x** [yearn/veYFI#61]
Is the process offchain or can you link where the votes are tally to distribute rewards later to gauges?

e.g

https://github.com/solidlyexchange/solidly/blob/eac1ef02ca8736138b25062c02646ea43d5bb6e4/contracts/BaseV1-voter.sol#L376

**Comment by pandadefi** [comment]
I think in our case it will be offchain.

**Comment by pandadefi** [comment]
Closing with the migration to off-chain voting.
