### ISSUE TITLE
Voter.sol question about weights and how they work?

### ISSUE THREAD

**Issue by storming0x** [yearn/veYFI#62]
Can the weights be any random number the user decides? in the curve contract is a bps based and limited up to 10K = 100%

https://github.com/yearn/veYfi/blob/d8fb8fc901bb4cac557377a0f35fff299ddb126d/contracts/Voter.sol#L118

How does it work here? I see its similar to solidly, but say if i vote with two vaults each with max uint256, and my ve weight 1

this would overflow right?
https://github.com/yearn/veYfi/blob/d8fb8fc901bb4cac557377a0f35fff299ddb126d/contracts/Voter.sol#L130

Which means there are numbers that dont make sense to vote with, i guess all weights need to add to less than the uint256 max?

So everybody has a budget of weight = max uint 256 and then given the ve global weight of the account and formula here :

https://github.com/yearn/veYfi/blob/d8fb8fc901bb4cac557377a0f35fff299ddb126d/contracts/Voter.sol#L136

thats gets adjusted down?

**Comment by pandadefi** [comment]
It seems you have answered to your questions already.
The power is an arbitrary number that gets summed and then readjusted using `_totalVoteWeight`

**Comment by pandadefi** [comment]
Closing with the migration to off-chain voting.
