### ISSUE TITLE
Voter.sol if enough accounts delegate to a single address, changing delegates may run out of gas

### ISSUE THREAD

**Issue by storming0x** [yearn/veYFI#63]
Here:

not sure but say if 10000 voters delegate to address 0x01 i think this loop to remove from delegation may revert w out of gas and voters cannot remove the address from delegation

https://github.com/yearn/veYfi/blob/d8fb8fc901bb4cac557377a0f35fff299ddb126d/contracts/Voter.sol#L257

Either we max the number of delegations an address can have or change the structure to be a mapping of mappings or another data structure that can scale the gas on the operations?

There are tradeoffs with both options, guessing the MAX delegations is the one that implies less changes

**Comment by 0xbok** [comment]
Does it make sense to have an additional mapping such that `map[_to][msg.sender]=i` where `i` is the index in the `delegateList` array? We can avoid the loop if we already know the index.

The drawback would be shorter loops can become costlier.

Similarly, it's managed by `gov` but `removeVaultFromRewards()` can also become a gas intensive operation if there are many vaults added to a gauge.
https://github.com/yearn/veYfi/blob/d8fb8fc901bb4cac557377a0f35fff299ddb126d/contracts/Voter.sol#L234

Here also, a mapping from vault to index can be created.

**Comment by pandadefi** [comment]
I do not expect that many people to delegate.  Writing storage is really expensive compared to just reading, we shouldn't create a new list

**Comment by rareweasel** [comment]
Idk if we have the total number of delegations we support without having an out of gas error, but most of the audit firms will ask us that question. Ideally, we need to know:

- Estimated gas consumption for 1-10 iteration.
- Calc an average per iteration.
- Max Iterations = MaxGasLimit / AvePerIteration

It applies for any scenario where we use fors/loops.

**Comment by pandadefi** [comment]
@0xbok you seem quite interested to work on gas problems.
Could you create an estimate of the gas estimation of changing the delegation for 1 - 10 - 100 delegates?
You can write a test and we can add it to the codebase to run it again if needed.

**Comment by 0xbok** [comment]
sounds good.

**Comment by rareweasel** [comment]
I'd also add in this analysis the Voter.vote/_vote function/s. It has 2 for/loops inside another for/loop.

![image](https://user-images.githubusercontent.com/89795397/157729092-0ef38442-59ea-4c1b-8860-6f9225ab87fa.png)

**Comment by 0xbok** [comment]
> @0xbok you seem quite interested to work on gas problems. Could you create an estimate of the gas estimation of changing the delegation for 1 - 10 - 100 delegates? You can write a test and we can add it to the codebase to run it again if needed.

For `delegate()`, I experimented with these tests https://github.com/0xbok/veYfi/commit/12c7f5d2c983db333b67112654eb991f007fd158. I have commented their gas consumption next to the specific call.

**Comment by 0xbok** [comment]
Should I write a PR to merge these tests? I can comment then so that we run them only when we need to estimate gas.

**Comment by pandadefi** [comment]
@0xbok you will have to rebase your changes to the latest master and please create a PR with the tests, do not comment them out.
