### ISSUE TITLE
Load array length in memory before looping

### ISSUE THREAD

**Issue by 0xbok** [yearn/veYfi#71]
https://github.com/yearn/veYfi/blob/4fab1224cd159735d2eb70a669efdd7527066218/contracts/Gauge.sol#L132

In cases like these, we can do:
```
uint256 len = extraRewards.length;
for (uint256 i = 0; i < len; i++) {
```

After updating all cases like these, `brownie test --gas` showed gas savings.

**Comment by pandadefi** [comment]
removeExtraReward isn't going to be called often, do you find other places that this changes can save gas?

**Comment by 0xbok** [comment]
Yes, here are the places we can make this change: https://github.com/0xbok/veYfi/commit/0438a34a25c78f8918832c2ec56073642a88948d
