### ISSUE TITLE
GaugeFactory.createGauge / Gauge.initialize: Events

### ISSUE THREAD

**Issue by rareweasel** [yearn/veYfi#73]
The graph processes the events in the order they were emitted.

That said, I would move the `GaugeCreated` event before `IGauge(newGauge).initialize(..)`, and would emit another new event `Initialized(
address _stakingToken,
        address _rewardToken,
        address _gov,
        address _rewardManager,
        address _ve,
        address _veYfiRewardPool
)` in `Gauge.initialize(...)`

![image](https://user-images.githubusercontent.com/89795397/157532785-d4c82e87-05b0-4e14-b92f-6684e2b95d45.png)

The graph takes a lot of time to process a RPC call (example view/pure functions), so if we have all the parameters in the event, we will not need to make these calls (like `gauge.stakingToken()` or `gauge.rewardToken()`).

**Comment by pandadefi** [comment]
https://github.com/yearn/veYfi/pull/90
