### ISSUE TITLE
Gauge.initialize: Change error messages

### ISSUE THREAD

**Issue by rareweasel** [yearn/veYfi#74]
I would use specific error messages in each require. 

![image](https://user-images.githubusercontent.com/89795397/157533084-3a40df0f-d00d-4331-a9da-cf3c569da344.png)

**Comment by pandadefi** [comment]
Find it a bit hard to have short messages but also make it explicative.

**Comment by 0xbok** [comment]
maybe we can use custom errors?

**Comment by pandadefi** [comment]
Yep that's what I was looking at, seems like a great option, I will have to do this on all contracts.

**Comment by rareweasel** [comment]
> Yep that's what I was looking at, seems like a great option, I will have to do this on all contracts.

Great Thanks @pandadefi

**Comment by pandadefi** [comment]
Using errors together with require is not yet supported
