### ISSUE TITLE
Gauge.removeExtraReward: Modify require

### ISSUE THREAD

**Issue by rareweasel** [yearn/veYfi#75]
As we discussed in tg, the require after the loop should be:

`require(index != type(uint256).max "extra reward not found");`

because `type(uint256).max` is the initial value for the index variable.

I'd also add a test to verify it.

Note: we also might use [EnumerableSet](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/release-v4.4/contracts/utils/structs/EnumerableSet.sol) to manage address arrays.

This contract guarantees:
- Elements are added, removed, and checked for existence in constant time (O(1)).
- Elements are enumerated in O(n). No guarantees are made on the ordering.

**Comment by pandadefi** [comment]
We don't need to add EnumerableSet for something that isn't going to be used on most cases.
https://github.com/yearn/veYfi/commit/3eb33104907949601f1a1574f2571ce733602739
