### ISSUE TITLE
Voter._vote: Gas consumption

### ISSUE THREAD

**Issue by rareweasel** [yearn/veYFI#77]
![image](https://user-images.githubusercontent.com/89795397/157728038-85d9990b-7dd8-4a42-b34e-ad65800b9cc9.png)

Would we save save gas if we emit only one event at the end passing two arrays (address[] gauges and uint256[] vaultWeights) ?

We would also add:
- _totalWeight
- _usedWeight

**Comment by pandadefi** [comment]
Excellent question. I will make some experiments.

**Comment by pandadefi** [comment]
I have created a test with 10 users and 2 gauges.
On master now voting for 2 gauges with 10 users costs:
1335133

**Comment by pandadefi** [comment]
If I want a single event I need to record the used weights and the gauges address.
```
        uint256[] memory accountWeights = new uint256[](_vaultCnt);
        address[] memory voteGauges = new address[](_vaultCnt);
 ```
 
 And adding this two gets me a `tack too deep, try removing local variables.` error.

**Comment by pandadefi** [comment]
Closing with the migration to off-chain voting.
