### ISSUE TITLE
BaseGauge.queueNewRewards: events

### ISSUE THREAD

**Issue by rareweasel** [yearn/veYfi#81]
![image](https://user-images.githubusercontent.com/89795397/157744693-a1e8dbee-1683-4ddd-a8d0-1362d31d3a3d.png)

I know we are emitting an event in the `_notifyRewardAmount` function, but afaik we are missing the new value for the `queuedRewards` variable (line 124, 134 and 136). Maybe we can include this value in the previous event, or add a new event here (like `RewardAmountNotified(uint256 queuedRewards)`).

**Comment by pandadefi** [comment]
https://github.com/yearn/veYfi/commit/ba1e8d72ff4274a61b12bc81fe0b47c668d7815b
