### ISSUE TITLE
VotingEscrow.create_lock/create_lock_for: events

### ISSUE THREAD

**Issue by rareweasel** [yearn/veYFI#85]
![image](https://user-images.githubusercontent.com/89795397/157748881-4d4e72d3-4255-49cc-a3b4-80da81bf9256.png)

I would add an event (example: LockCreated(user, value, unlock_time))

**Comment by pandadefi** [comment]
That would be a duplicate with this:

https://github.com/yearn/veYfi/blob/master/contracts/VotingEscrow.vy#L414
