### ISSUE TITLE
VotingEscrow.increase_unlock_time: events

### ISSUE THREAD

**Issue by rareweasel** [yearn/veYFI#87]
![image](https://user-images.githubusercontent.com/89795397/157749883-87906d2a-3f26-4991-8814-90330acfc513.png)

I would add an event with user address and new lock time.

**Comment by pandadefi** [comment]
this is logged here:
https://github.com/yearn/veYfi/blob/master/contracts/VotingEscrow.vy#L414

**Comment by rareweasel** [comment]
Closing issue
